"""Create MONAI datalists from nnU-Net folds and a case-information CSV.

Run ``python -m shared_modules.datalists --help`` for the command-line interface.
Only Python's standard library is required.
"""

import argparse
import csv
import json
from pathlib import Path


def load_case_info(csv_path):
    """Index CSV rows by patient_id_study_id, preserving leading zeros.

    Only patient_id and study_id are mandatory. A nonempty case_csPCa value
    is converted to case_pca (0/1); other clinical fields are not exported.
    """
    cases = {}
    with Path(csv_path).open(newline="", encoding="utf-8-sig") as stream:
        reader = csv.DictReader(stream)
        if not {"patient_id", "study_id"}.issubset(reader.fieldnames or []):
            raise ValueError("Case CSV must contain patient_id and study_id columns")
        for line, row in enumerate(reader, start=2):
            patient_id = (row["patient_id"] or "").strip()
            study_id = (row["study_id"] or "").strip()
            if not patient_id or not study_id:
                raise ValueError(f"Missing patient_id or study_id on CSV line {line}")
            if any(c in patient_id + study_id for c in "/\\"):
                raise ValueError(f"Invalid identifier on CSV line {line}")
            case_id = f"{patient_id}_{study_id}"
            if case_id in cases:
                raise ValueError(f"Duplicate case in CSV: {case_id}")
            case = {"patient_id": patient_id, "study_id": study_id}
            status = (row.get("case_csPCa") or "").strip().upper()
            if status:
                statuses = {"NO": 0, "YES": 1, "0": 0, "1": 1,
                            "FALSE": 0, "TRUE": 1}
                if status not in statuses:
                    raise ValueError(f"Invalid case_csPCa for {case_id}: {status!r}")
                case["case_pca"] = statuses[status]
            cases[case_id] = case
    if not cases:
        raise ValueError("Case CSV contains no cases")
    return cases


def create_datalists(
    splits_path,
    csv_path,
    images_dir,
    labels_dir,
    *,
    sequence_ids=(0, 1, 2),
    prostate_dir=None,
    prostate_pred_dir=None,
    prostate_pred_suffix="_pred",
    zones_dir=None,
    check_files=False,
    data_dir=".",
):
    """Return {fold_index: {training: [...], validation: [...], test: []}}.

    splits_path must contain a JSON array of {train: [...], val: [...]} folds.
    Entries may be patient IDs (expanding to all their CSV studies) or full
    patient_id_study_id case IDs. Split order and CSV study order are retained.
    Duplicate cases and patients shared between train and val are rejected.

    Image names are {case_id}_{sequence_id:04d}.nii.gz; cancer, whole-gland
    prostate, and zonal labels are {case_id}.nii.gz. prostate_dir adds the
    whole-gland mask as prostate, independently of prostate_pred_dir.
    Prostate predictions default to {case_id}_pred.nii.gz.
    sequence_ids are in model-channel order (default: T2W, ADC, HBV).

    Directory paths are stored as supplied, suitable for resolving relative
    paths against config.data.data_dir. If check_files is True, data_dir is
    the base directory used to verify all referenced files before returning.
    No images or labels are generated by this function.
    """
    sequence_ids = tuple(sequence_ids)
    if (len(sequence_ids) != 3 or len(set(sequence_ids)) != 3
            or any(type(s) is not int or s < 0 for s in sequence_ids)):
        raise ValueError("sequence_ids must contain three distinct nonnegative integers")
    cases = load_case_info(csv_path)
    patients = {}
    for case_id, case in cases.items():
        patients.setdefault(case["patient_id"], []).append(case_id)
    with Path(splits_path).open(encoding="utf-8") as stream:
        folds = json.load(stream)
    if not isinstance(folds, list) or not folds:
        raise ValueError("Splits JSON must be a nonempty array of train/val folds")

    def expand(identifiers, fold_index, split):
        if not isinstance(identifiers, list):
            raise ValueError(f"Fold {fold_index} {split} must be a list of IDs")
        result, seen = [], set()
        for identifier in identifiers:
            if type(identifier) not in (str, int):
                raise ValueError(f"Invalid ID in fold {fold_index} {split}: {identifier!r}")
            identifier = str(identifier).strip()
            if identifier in cases:
                matching = [identifier]
            elif identifier in patients:
                matching = patients[identifier]
            else:
                raise ValueError(f"Unknown ID in fold {fold_index} {split}: {identifier}")
            for case_id in matching:
                if case_id in seen:
                    raise ValueError(f"Duplicate case in fold {fold_index} {split}: {case_id}")
                seen.add(case_id)
                result.append(case_id)
        return result

    def make_entry(case_id):
        entry = {
            "image": [(Path(images_dir) / f"{case_id}_{s:04d}.nii.gz").as_posix()
                      for s in sequence_ids],
            "pca": (Path(labels_dir) / f"{case_id}.nii.gz").as_posix(),
        }
        if "case_pca" in cases[case_id]:
            entry["case_pca"] = cases[case_id]["case_pca"]
        if prostate_dir is not None:
            entry["prostate"] = (Path(prostate_dir) / f"{case_id}.nii.gz").as_posix()
        if prostate_pred_dir is not None:
            entry["prostate_pred"] = (
                Path(prostate_pred_dir) / f"{case_id}{prostate_pred_suffix}.nii.gz"
            ).as_posix()
        if zones_dir is not None:
            entry["zones"] = (Path(zones_dir) / f"{case_id}.nii.gz").as_posix()
        if check_files:
            paths = entry["image"] + [entry[k] for k in ("pca", "prostate", "prostate_pred", "zones")
                                      if k in entry]
            for path in paths:
                resolved = Path(data_dir) / path
                if not resolved.is_file():
                    raise FileNotFoundError(f"Missing file for {case_id}: {resolved}")
        return entry

    datalists = {}
    for index, fold in enumerate(folds):
        if not isinstance(fold, dict) or not {"train", "val"}.issubset(fold):
            raise ValueError(f"Fold {index} must contain train and val lists")
        training = expand(fold["train"], index, "train")
        validation = expand(fold["val"], index, "val")
        train_patients = {cases[c]["patient_id"] for c in training}
        val_patients = {cases[c]["patient_id"] for c in validation}
        overlap = train_patients & val_patients
        if overlap:
            raise ValueError(f"Patients in both train and val for fold {index}: "
                             + ", ".join(sorted(overlap)))
        datalists[index] = {
            "training": [make_entry(c) for c in training],
            "validation": [make_entry(c) for c in validation],
            "test": [],
        }
    return datalists


def write_datalists(datalists, output_dir):
    """Write fold_0.json, fold_1.json, ... and return their paths.

    Existing fold files at these paths are replaced.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    paths = []
    for index, datalist in datalists.items():
        path = output_dir / f"fold_{index}.json"
        path.write_text(json.dumps(datalist, indent=4) + "\n", encoding="utf-8")
        paths.append(path)
    return paths


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--splits", required=True, type=Path)
    parser.add_argument("--cases-csv", required=True, type=Path)
    parser.add_argument("--images-dir", required=True, type=Path,
                        help="Image directory; spelling/case must match your imagesTr or imagesTR folder")
    parser.add_argument("--labels-dir", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--sequence-ids", nargs=3, type=int, default=(0, 1, 2),
                        help="Sequence numbers in T2W, ADC, HBV order (default: 0 1 2)")
    parser.add_argument("--prostate-dir", type=Path,
                        help="Whole-gland mask directory; filenames are {patient_id}_{study_id}.nii.gz")
    parser.add_argument("--prostate-pred-dir", type=Path)
    parser.add_argument("--prostate-pred-suffix", default="_pred",
                        help="Suffix before .nii.gz for prostate predictions (default: _pred)")
    parser.add_argument("--zones-dir", type=Path)
    parser.add_argument("--check-files", action="store_true")
    parser.add_argument("--data-dir", type=Path, default=Path("."),
                        help="Base for checking relative paths; use config.data.data_dir")
    args = parser.parse_args()
    try:
        datalists = create_datalists(
            args.splits, args.cases_csv, args.images_dir, args.labels_dir,
            sequence_ids=args.sequence_ids,
            prostate_dir=args.prostate_dir,
            prostate_pred_dir=args.prostate_pred_dir,
            prostate_pred_suffix=args.prostate_pred_suffix,
            zones_dir=args.zones_dir,
            check_files=args.check_files,
            data_dir=args.data_dir,
        )
    except (ValueError, OSError) as error:
        parser.error(str(error))
    for path, datalist in zip(write_datalists(datalists, args.output_dir), datalists.values()):
        print(f"{path}: {len(datalist['training'])} training, "
              f"{len(datalist['validation'])} validation")


if __name__ == "__main__":
    main()
